name: kidnap_detection_app
description: kidnap detector app.

publish_to: "none"

version: 0.0.101+101

environment:
  sdk: ">=2.19.0 <3.10.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  dio: ^4.0.6
  flutter_modular: ^5.0.3
  mobx: ^2.1.4
  video_player: ^2.2.5
  video_player_win: ^1.1.0
  flutter_mobx: ^2.0.6+5
  socket_io_client: ^2.0.2
  screenshot: ^2.1.0
  flutter_screenutil:
  provider:
  msgpack_dart:
  google_fonts: ^5.0.0
  expandable: ^5.0.1
  path_provider: ^2.0.15


dev_dependencies:
  build_runner:
  flutter_gen_runner:

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/
    - assets/images/
    - assets/camera/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal.ttf
